; ============================================================
; LNAYCRM - logger.conf
; ============================================================

[general]
appendhostname=no
rotatestrategy=rotate
exec_after_rotate=gzip -9 ${filename}.2

[logfiles]
; Console : warnings + erreurs seulement
console => warning,error
; Fichier principal
/var/log/asterisk/full => notice,warning,error,verbose(3)
; Fichier sécurité
/var/log/asterisk/security => security
; CDR messages
/var/log/asterisk/cdr-csv/Master.csv => cdr
