; ============================================================
; LNAYCRM — queues.conf (file d'attente vente simulation locale)
; ============================================================

[general]
persistentmembers = yes
autofill          = yes
monitor-type      = MixMonitor

[sales]
strategy          = ringall
timeout           = 30
retry             = 5
wrapuptime        = 10
maxlen            = 0
announce-frequency = 0
member            => PJSIP/1001
member            => PJSIP/1002
member            => PJSIP/1003
member            => PJSIP/1004
member            => PJSIP/1005
