; ============================================================
; LNAYCRM — http.conf
; Serveur HTTP intégré Asterisk (ARI + WebRTC WS)
; ============================================================

[general]
enabled         = yes
bindaddr        = 0.0.0.0
bindport        = 8088
tlsenable       = yes
tlsbindport     = 8089
tlscertfile     = /etc/asterisk/keys/asterisk.crt
tlsprivatekey   = /etc/asterisk/keys/asterisk.key
; prefix        = asterisk    ; optionnel : /asterisk/ari/...
enablestatic    = yes
